### ISSUE TITLE
Crash when encountering blocks without "waterlogged" property

### ISSUE THREAD

**Issue by Stikulzon** [Felicis/Water-Physics-Overhaul#54]
Water WPO crashes when interacting with blocks that do not have the waterlogged property. This happens because WPO tries to set the waterlogged state for any block I try to place water into, regardless of whether the block supports this property.

Example with TerraFirmaCraft:
1. I try to place a water into rock

https://github.com/Felicis/Water-Physics-Overhaul/assets/24866243/e12ce1b6-071e-4bd6-92f6-b5c5effcc5b8
2. Minecraft crashes with a repeating error:
```
[SKDS-Worker-1/ERROR] [ne.sk.co.SKDSCore/]: Exeption while executing task 
java.lang.IllegalArgumentException: Cannot set property BooleanProperty{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{tfc:rock/spike/schist}
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:122) ~[client-1.20.1-20230612.114412-srg.jar%23304!/:?] {re:mixin,pl:connector_pre_launch:A,re:computing_frames,pl:rei_plugin_compatibilities:B,pl:connector_pre_launch:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin from mod ferritecore,pl:mixin:A,pl:connector_pre_launch:A}
	at net.skds.wpo.fluidphysics.FFluidStatic.getUpdatedState(FFluidStatic.java:103) ~[water_physics_overhaul-1.20.1-0.3.1.jar%23303!/:0.3.1] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.skds.wpo.fluidphysics.FFluidBasic.getUpdatedState(FFluidBasic.java:338) ~[water_physics_overhaul-1.20.1-0.3.1.jar%23303!/:0.3.1] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.skds.wpo.fluidphysics.FFluidBasic.flowFullCube(FFluidBasic.java:332) ~[water_physics_overhaul-1.20.1-0.3.1.jar%23303!/:0.3.1] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.skds.wpo.fluidphysics.FFluidDefault.execute(FFluidDefault.java:128) ~[water_physics_overhaul-1.20.1-0.3.1.jar%23303!/:0.3.1] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.skds.wpo.fluidphysics.FFluidBasic.run(FFluidBasic.java:133) ~[water_physics_overhaul-1.20.1-0.3.1.jar%23303!/:0.3.1] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.skds.wpo.fluidphysics.FluidTask$DefaultTask.run(FluidTask.java:66) ~[water_physics_overhaul-1.20.1-0.3.1.jar%23303!/:0.3.1] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.skds.core.multithreading.UniversalWorkerThread.takeTasksStack(UniversalWorkerThread.java:79) ~[skds_core-1.20.1-0.3.0.jar%23292!/:0.3.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.skds.core.multithreading.UniversalWorkerThread.run(UniversalWorkerThread.java:51) ~[skds_core-1.20.1-0.3.0.jar%23292!/:0.3.0] {re:classloading,pl:rei_plugin_compatibilities:B}
```

**Comment by xJiggo** [comment]
Thanks for this information this will help with debugging and solving the issue
